src/BBBS_STEM/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('bs_theme.urls')), # Root URL
    url(r'^polls/', include('polls.urls')),
	url(r'^bs_theme/', include('bs_theme.urls')),
    url(r'^admin/', admin.site.urls),
]

src/bs_theme/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from . import views

app_name = 'bs_theme'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^challenges/$', views.challenge_list, name='challenges'),
    url(r'^caesar_i/$', views.caesar_i, name='caesar_i'),
    url(r'^caesar_i/(?P<rotate>\d+)', views.caesar_i, name='caesar_i'),
    url(r'^caesar_ii/$', views.caesar_ii, name='caesar_ii'),
    url(r'^caesar_ii/(?P<rotate>\d+)', views.caesar_ii, name='caesar_ii'),
    url(r'^register/$', CreateView.as_view(
            template_name='registration_form.html',
            form_class=UserCreationForm,
            success_url='/'
    )),
    url(r'^accounts/register/$', views.register, name='register'),
]

src/polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

src/bs_theme/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models

class Post(models.Model):
	title = models.CharField(max_length=120)
	content = models.TextField()
	updated = models.DateTimeField(auto_now=True, auto_now_add=False)
	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

	def __str__(self):
		return self.title

class Challenge(models.Model):
	title = models.CharField(max_length=120)
	content = models.TextField()
	points_value = models.PositiveSmallIntegerField()
	updated = models.DateTimeField(auto_now=True, auto_now_add=False)
	points_limited = models.BooleanField(default=True)
	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

	def __str__(self):
		return self.title

class UserScore(models.Model):
    user_id = models.OneToOneField(User, on_delete=models.CASCADE)
    score = models.PositiveIntegerField(default=0)

    def __str__(self):
    	return '{\'user_id\': \'%s\', \'score\': %s}' % (self.user, self.score)

# class BsThemeAdmin(admin.ModelAdmin):
# 	pass

src/polls/models.py
#from __future__ import unicode_literals
import datetime

from django.db import models
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible

@python_2_unicode_compatible
class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')

	def was_published_recently(self):
		return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

	def __str__(self):
		return self.question_text

@python_2_unicode_compatible
class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)

	def __str__(self):
		return self.choice_text

src/bs_theme/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response
from django.shortcuts import render
from django.views.generic.edit import FormView 
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from .models import UserScore, Challenge
from django.db.models import Count
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from .challenges import Challenges
import random

def index(request):
    top_users = UserScore.objects.order_by('-score')[:5]
    context = {'top_users': top_users}
    return render(request, 'bs_theme/index.html', context)

def challenge_list(request):
    items = Challenge.objects.order_by('id')
    context = {'problems': items}
    return render(request, 'bs_theme/challenge_list.html')

def caesar_i(request, rotate='', plaintext=''):
    challenge = Challenge.objects.filter(id=1)
    choices = []
    for x in range(1,27):
        choices.append(x)
    context = {'challenge':challenge, 'choices': choices}

    if request.method == 'GET':
        data = request.GET
        plaintext = data.get('pt')
        rotate = str(data.get('rot'))
        user_id = data.get('user_id')
        c = Challenges()
        ct = c.caesar_i(rotate, plaintext, user_id)
        context.update({'pt':plaintext, 'rot':rotate, 'ct':ct})
    return render(request, 'bs_theme/caesar_i.html', context)

def caesar_ii(request):
    c = Challenges()
    challenge = Challenge.objects.filter(id=2)
    choices = []
    for x in range(1,27):
        choices.append(x)

    answer_pt = 'www.secretstash.com'

    if request.method == 'GET':
        data = request.GET
        user_pt = data.get('user_pt')
        user_rot = str(data.get('user_rot'))
        answer_rot = data.get('answer_rot')
        answered = data.get('answered')
        print answered
        print 'pre answer_rot: ' + str(answer_rot)
        if not answer_rot or answered:
            answer_rot = random.randint(1,26)
        print answer_rot
        answer_ct = c.get_caesar(answer_rot, answer_pt)
        context = {'challenge':challenge,
            'choices': choices,
            'answer_ct':answer_ct,
            'answer_rot': answer_rot}

        user_id = data.get('user_id')
        c = Challenges()
        correct = c.caesar_ii(user_pt, user_rot, answer_pt, answer_rot, user_id)
        if correct:
            context.update({'correct':correct})

    return render(request, 'bs_theme/caesar_ii.html', context)

def login(request):
	return render(request, 'bs_theme/login.html')

def logout(request):
    auth_logout(request)
    return render(request, 'logout.html')

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/login')

    else:
        form = UserCreationForm()

    return render(request, 'registration/registration_form.html', {'form':form})

def registration_complete(request):
    return render (request, '../../index.html')

@receiver(post_save, sender=User)
def init_new_user(sender, **kwargs):
    user = kwargs.get('instance')
    user_score = UserScore(user_id=user, score=0)
    try:
        user_score.save()
    except:
        pass

src/polls/views.py
from django.http import Http404
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.views import generic
from django.shortcuts import get_object_or_404, render

from django.db.models import F
from .models import Question, Choice

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes = F('votes') + 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

src/bs_theme/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="{% static 'css/bootstrap-theme.min.css' %}" rel="stylesheet">
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <!--<link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">-->

    <!-- Custom styles for this template -->
    <link href="{% static 'bs_theme/theme.css' %}" rel="stylesheet">  

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <!-- // <script src="../../assets/js/ie-emulation-modes-warning.js"></script> -->

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <!-- Fixed navbar -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'bs_theme:index' %}">Crypto and Code Breaking</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'bs_theme:index' %}">Lecture</a></li>
            <!-- <li><a href="{% url 'bs_theme:challenges' %}">Challenges</a></li> -->
            <li><a href="{% url 'bs_theme:register' %}">Register</a></li>
            <li><a href="{% url 'bs_theme:login' %}">Log In</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown Nav<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'bs_theme:logout' %}">Log Out</a></li>
                <li><a href="{% url 'bs_theme:index' %}">Home</a></li>
                <!-- <li><a href="{% url 'bs_theme:challenges' %}">Challenges</a></li> -->
                <li><a href="#">Lecture</a></li>
                {% if user.is_authenticated %}
                <li role="separator" class="divider"></li>
                <li class="dropdown-header">Challenges</li>
                <li><a href="{% url 'bs_theme:caesar_i' %}">Caesar Cipher 1</a></li>
                <li><a href="{% url 'bs_theme:caesar_ii' %}">Caesar Cipher 2</a></li>
                {% endif %}
              </ul>
            </li>
            {% if user.is_authenticated %}
              <li><a class="right-side-button" href="#">{{ user.get_username }}</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    {% block content %}
    {% endblock %}


    <!-- Core Scripts - Include with every page -->
    <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
    <!-- // <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script> -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block javascript %}
    {% endblock %}

    </body>
</html>

src/bs_theme/templates/bs_theme/caesar_i.html
{% extends 'base.html' %}
{% block title %}
  Caesar 1 Challenge
{% endblock %}
{% block content %}
	<div class="container theme-showcase" role="main">
		{% for c in challenge %}
		<h2>{{ c.title }}</h2>
		<p> {{ c.content }}
		{% endfor %}
		<form action="{% url 'bs_theme:caesar_i' %}" method="get">
            <!-- {% csrf_token %} -->
              <div class="form-group">
			    <label for="plaintext">Plaintext: </label>
			    <input type="hidden" class="form-control" id="user_id" aria-describedby="emailHelp" name="user_id" value="{{ user.id }}">
			    <input type="text" class="form-control" id="plaintext" aria-describedby="emailHelp" placeholder="Enter plain text to be enciphered" name="pt">
			      <div class="form-group">
				    <label for="rotate">Rotate Value: </label>
				    <select multiple class="form-control" id="rot" name="rot">
				    	{% for x in choices %}
				     	<option>{{ x }}</option>
				     	{% endfor %}
				    </select>
  				</div>
			    <button type="submit" class="btn btn-primary">Encrypt</button>
			</br>
			    <large id="ciphertext" class="form-text text-muted">Plainttext: {{ pt }}</large>
			</br>
			    <large id="ciphertext" class="form-text text-muted">Ciphertext: {{ ct }}</large>
			  </div>
		</form>
	</div>
{% endblock %}

src/bs_theme/templates/bs_theme/caesar_ii.html
{% extends 'base.html' %}
{% block title %}
  Caesar 2 Challenge
{% endblock %}
{% block content %}
	<div class="container theme-showcase" role="main">
		{% for c in challenge %}
		<h2>{{ c.title }}</h2>
		<p> {{ c.content }}
		{% endfor %}
		<form action="{% url 'bs_theme:caesar_ii' %}" method="get">
            <!-- {% csrf_token %} -->
              <div class="form-group">
              	<h4>CipherText: {{ answer_ct }}</h4>
			    <label for="plaintext">Deciphered Code: </label>
			    <input type="hidden" class="form-control" id="user_id" aria-describedby="emailHelp" name="user_id" value="{{ user.id }}">
			    <input type="hidden" class="form-control" id="answer_rot" aria-describedby="emailHelp" name="answer_rot" value="{{ answer_rot }}">
			    {% if correct %}
			    <input type="hidden" class="form-control" id="answered" aria-describedby="emailHelp" name="answered" value="{{ answer_rot }}">
			    {% endif %}
			    <input type="text" class="form-control" id="user_pt" aria-describedby="emailHelp" placeholder="Enter plain text to be enciphered" name="user_pt">
			      <div class="form-group">
				    <label for="rotate">Rotate Value: </label>
				    <select multiple class="form-control" id="user_rot" name="user_rot">
				    	{% for x in choices %}
				     	<option>{{ x }}</option>
				     	{% endfor %}
				    </select>
  				</div>
			    <button type="submit" class="btn btn-primary">Check Answer</button>
			  </div>
		</form>
		{% if correct %}
			<h4>Correct</h4>
		{% endif %}
	</div>
{% endblock %}

src/bs_theme/templates/bs_theme/challenge_list.html
{% extends 'base.html' %}
{% block title %}
	Points for Challenges
{% endblock %}
{% block content %}
<div class="container theme-showcase panel panel-default panel-group" id="accordion">
  <h1>Earn Points With These Challenges</h1>
  {% for problem in problems %}
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapse{{ problem.id }}">
        {{ problem.title }}</a>
      </h4>
    </div>
    <div id="collapse{{ problem.id }}" class="panel-collapse collapse in">
      <div class="panel-body">{{ problem.content }}</div>
    </div>
  </div>
  {% endfor %}
</div> 
{% endblock %}

src/bs_theme/templates/bs_theme/index.html
{% extends 'base.html' %}
{% block title %}
  Intro to Crypto and Code Breaking
{% endblock %}
{% block content %}
    <div class="container theme-showcase" role="main">

      <!-- Main jumbotron for a primary marketing message or call to action -->
      <div class="jumbotron">
        <h1>An Introduction to Cryptography and Code Breaking</h1>
        <p>Feel free to follow along on screen or with your personal mobile device by pointing your browser to 192.168.1.23</p>
      </br>
        <p>This demonstration will cover the very first use of codes in recorded history and how to break those codes.  There will also be a brief look at how Euclid's algorithm for finding relative primes between two large prime numbers is used in todays industry standard cryptographic algorithms.</p>
      </br>
        <p>Other topics included in this presentation:</p>
        <ul>
          <li>Why a degree in Computer Science and / or Math is important for Cryptography and Information Security careers</li>
          <li>Raspberry Pi Computer and GPIO (general purpose input / output) Pins used to control LED's (light emitting diodes) based on user input from web app</li>
          <li>Development of this Web Application</li>
        </ul>
      </div>


      <div class="page-header">
        <h1>Leader Board</h1>
      </div>
      <div class="row">
        <div class="col-md-6">
          <table class="table table-condensed">
            <thead>
              <tr>
                <th>Username</th>
                <th>Score</th>
              </tr>
            </thead>
            <tbody>

              {% for tu in top_users %}
                <tr>
                  <td>{{ tu.user_id }}</td>
                  <td>{{ tu.score }}</td>
                </tr>
              {% endfor %}

            </tbody>
          </table>
        </div>
      </div>
{% endblock %}

src/bs_theme/templates/bs_theme/lecture_list.html
<div id="accordion" role="tablist" aria-multiselectable="true">
  <div class="card">
    <div class="card-header" role="tab" id="headingOne">
      <h5 class="mb-0">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          Brief Background
        </a>
      </h5>
    </div>
    <div id="collapseOne" class="collapse in" role="tabpanel" aria-labelledby="headingOne">
      <div class="card-block">
        <ul>
          <li>Former Marine Infantryman</li>
          <li>Recent graduate in Computer Science with minor in Mathematics from MSUD</li>
          <li>Been working in tech industry for about 3 years</li>
        </ul>
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header" role="tab" id="headingTwo">
      <h5 class="mb-0">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Caesar Cipher
        </a>
      </h5>
    </div>
    <div id="collapseTwo" class="collapse" role="tabpanel" aria-labelledby="headingTwo">
      <div class="card-block">
        <ul>
          <li>Used by Julius Caesar around 50 BC for military communications</li>
          <li>It is a shift cipher where letters are rotated to a certain degree based on the key.  The key tells how many letters to shift to create the cipher text</li>
          <li>ROT 13 is a widely known cipher using the same algortithm as the Caesar Cipher, but only allows shift of 13</li>
          <li>Can be broken easily with word analysis.  Think about the frequency of each letter used in our language.  Hint: Vowels are highest.</li>
        </ul>
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header" role="tab" id="headingThree">
      <h5 class="mb-0">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          Vegenere
        </a>
      </h5>
    </div>
    <div id="collapseThree" class="collapse" role="tabpanel" aria-labelledby="headingThree">
      <div class="card-block">
        <ul>
          <li>Uses Caesar Ciphere / Character Rotation</li>
          <li>Not susceptible to character analysis like Caesar Cipher is</ul>
          <li>Enigma Machine / Imitation Game Movie</li>
        </ul>
      </div>
    </div>
  </div>  
  <div class="card">
    <div class="card-header" role="tab" id="headingThree">
      <h5 class="mb-0">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          Euclid / RSA / Public Key Cryptography
        </a>
      </h5>
    </div>
    <div id="collapseThree" class="collapse" role="tabpanel" aria-labelledby="headingThree">
      <div class="card-block">
        <ul>
          <li>Euclid developed an algorithm for finding the Greatest Common Devisior of any prime number in 300 BC</li>
          <li>Today we are still using that algorithm for our most used cryptographic algorithms today, RSA</ul>
          <li>Amount of computing power needed to break these codes is astronomical, literally</li>
        </ul>
      </div>
    </div>
  </div>
</div>

src/polls/templates/polls/detail.html
<h1> {{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

src/polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Bootstrap 101 Template</title>

    <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <h1>Hello, world!</h1>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
  </body>
</html>

src/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>